apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: geeksbank-core-cicd
spec:

  serviceAccountName: tekton-pipelines

  pipelineRef:
    name: geeksbank-cicd

  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  params:
    # git params
    - name: repo-url
      value: ssh://APKARC2VFMSWTOP72NHJ@git-codecommit.us-east-1.amazonaws.com/v1/repos/GeeksBank.Core.Service
    - name: branch-name
      value: develop

    # helm params
    - name: values_path
      value: repo/.docker/envs/prod.yaml
    - name: charts_dir
      value: repo/.docker/geeksbank-core
    - name: values_path
      value: repo/.docker/envs/develop.yaml
    - name: release_version
      value: v1.0.0
    - name: release_namespace
      value: geeksbank-micros
    - name: release_name
      value: geeksbank-core

    # docker params
    - name: IMAGE
      value: 074803668141.dkr.ecr.us-west-2.amazonaws.com/geeksbank-core
    - name: CONTEXT
      value: "repo/"
    - name: DOCKERFILE
      value: "$(workspaces.source.path)/repo/.docker/Dockerfile"
