{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-envs
type: Opaque
data:
  {{- range $key,$value := .Values.secrets}}
  {{ $key }} : {{ $value }}
  {{- end}}
{{- end}}