apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ required "A valid .Values.service.ports[].name entry required!" .name  }}
      port: {{ required "A valid .Values.service.ports[].port entry required!" .port }}
      protocol: {{ .protocol | default "TPC"  }}
      targetPort: {{ .targetPort | default .port }}
    {{- end }}
  selector:
    app: {{.Release.Name}}
