// <auto-generated />
using GeeksBank.Core.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeeksBank.Core.Api.Migrations
{
    [DbContext(typeof(GeeksBankDbContext))]
    [Migration("20220327163909_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GeeksBank.Core.Infrastructure.Models.Fibonacci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Fibonacci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 0L
                        },
                        new
                        {
                            Id = 2,
                            Number = 1L
                        },
                        new
                        {
                            Id = 3,
                            Number = 1L
                        },
                        new
                        {
                            Id = 4,
                            Number = 2L
                        },
                        new
                        {
                            Id = 5,
                            Number = 3L
                        },
                        new
                        {
                            Id = 6,
                            Number = 5L
                        },
                        new
                        {
                            Id = 7,
                            Number = 8L
                        },
                        new
                        {
                            Id = 8,
                            Number = 13L
                        },
                        new
                        {
                            Id = 9,
                            Number = 21L
                        },
                        new
                        {
                            Id = 10,
                            Number = 34L
                        },
                        new
                        {
                            Id = 11,
                            Number = 55L
                        },
                        new
                        {
                            Id = 12,
                            Number = 89L
                        },
                        new
                        {
                            Id = 13,
                            Number = 144L
                        },
                        new
                        {
                            Id = 14,
                            Number = 233L
                        },
                        new
                        {
                            Id = 15,
                            Number = 377L
                        },
                        new
                        {
                            Id = 16,
                            Number = 610L
                        },
                        new
                        {
                            Id = 17,
                            Number = 987L
                        },
                        new
                        {
                            Id = 18,
                            Number = 1597L
                        },
                        new
                        {
                            Id = 19,
                            Number = 2584L
                        },
                        new
                        {
                            Id = 20,
                            Number = 4181L
                        },
                        new
                        {
                            Id = 21,
                            Number = 6765L
                        },
                        new
                        {
                            Id = 22,
                            Number = 10946L
                        },
                        new
                        {
                            Id = 23,
                            Number = 17711L
                        },
                        new
                        {
                            Id = 24,
                            Number = 28657L
                        },
                        new
                        {
                            Id = 25,
                            Number = 46368L
                        },
                        new
                        {
                            Id = 26,
                            Number = 75025L
                        },
                        new
                        {
                            Id = 27,
                            Number = 121393L
                        },
                        new
                        {
                            Id = 28,
                            Number = 196418L
                        },
                        new
                        {
                            Id = 29,
                            Number = 317811L
                        },
                        new
                        {
                            Id = 30,
                            Number = 514229L
                        },
                        new
                        {
                            Id = 31,
                            Number = 832040L
                        },
                        new
                        {
                            Id = 32,
                            Number = 1346269L
                        },
                        new
                        {
                            Id = 33,
                            Number = 2178309L
                        },
                        new
                        {
                            Id = 34,
                            Number = 3524578L
                        },
                        new
                        {
                            Id = 35,
                            Number = 5702887L
                        },
                        new
                        {
                            Id = 36,
                            Number = 9227465L
                        },
                        new
                        {
                            Id = 37,
                            Number = 14930352L
                        },
                        new
                        {
                            Id = 38,
                            Number = 24157817L
                        },
                        new
                        {
                            Id = 39,
                            Number = 39088169L
                        },
                        new
                        {
                            Id = 40,
                            Number = 63245986L
                        },
                        new
                        {
                            Id = 41,
                            Number = 102334155L
                        },
                        new
                        {
                            Id = 42,
                            Number = 165580141L
                        },
                        new
                        {
                            Id = 43,
                            Number = 267914296L
                        },
                        new
                        {
                            Id = 44,
                            Number = 433494437L
                        },
                        new
                        {
                            Id = 45,
                            Number = 701408733L
                        },
                        new
                        {
                            Id = 46,
                            Number = 1134903170L
                        },
                        new
                        {
                            Id = 47,
                            Number = 1836311903L
                        },
                        new
                        {
                            Id = 48,
                            Number = -1323752223L
                        },
                        new
                        {
                            Id = 49,
                            Number = 512559680L
                        },
                        new
                        {
                            Id = 50,
                            Number = -811192543L
                        },
                        new
                        {
                            Id = 51,
                            Number = -298632863L
                        },
                        new
                        {
                            Id = 52,
                            Number = -1109825406L
                        },
                        new
                        {
                            Id = 53,
                            Number = -1408458269L
                        },
                        new
                        {
                            Id = 54,
                            Number = 1776683621L
                        },
                        new
                        {
                            Id = 55,
                            Number = 368225352L
                        },
                        new
                        {
                            Id = 56,
                            Number = 2144908973L
                        },
                        new
                        {
                            Id = 57,
                            Number = -1781832971L
                        },
                        new
                        {
                            Id = 58,
                            Number = 363076002L
                        },
                        new
                        {
                            Id = 59,
                            Number = -1418756969L
                        },
                        new
                        {
                            Id = 60,
                            Number = -1055680967L
                        },
                        new
                        {
                            Id = 61,
                            Number = 1820529360L
                        },
                        new
                        {
                            Id = 62,
                            Number = 764848393L
                        },
                        new
                        {
                            Id = 63,
                            Number = -1709589543L
                        },
                        new
                        {
                            Id = 64,
                            Number = -944741150L
                        },
                        new
                        {
                            Id = 65,
                            Number = 1640636603L
                        },
                        new
                        {
                            Id = 66,
                            Number = 695895453L
                        },
                        new
                        {
                            Id = 67,
                            Number = -1958435240L
                        },
                        new
                        {
                            Id = 68,
                            Number = -1262539787L
                        },
                        new
                        {
                            Id = 69,
                            Number = 1073992269L
                        },
                        new
                        {
                            Id = 70,
                            Number = -188547518L
                        },
                        new
                        {
                            Id = 71,
                            Number = 885444751L
                        },
                        new
                        {
                            Id = 72,
                            Number = 696897233L
                        },
                        new
                        {
                            Id = 73,
                            Number = 1582341984L
                        },
                        new
                        {
                            Id = 74,
                            Number = -2015728079L
                        },
                        new
                        {
                            Id = 75,
                            Number = -433386095L
                        },
                        new
                        {
                            Id = 76,
                            Number = 1845853122L
                        },
                        new
                        {
                            Id = 77,
                            Number = 1412467027L
                        },
                        new
                        {
                            Id = 78,
                            Number = -1036647147L
                        },
                        new
                        {
                            Id = 79,
                            Number = 375819880L
                        },
                        new
                        {
                            Id = 80,
                            Number = -660827267L
                        },
                        new
                        {
                            Id = 81,
                            Number = -285007387L
                        },
                        new
                        {
                            Id = 82,
                            Number = -945834654L
                        },
                        new
                        {
                            Id = 83,
                            Number = -1230842041L
                        },
                        new
                        {
                            Id = 84,
                            Number = 2118290601L
                        },
                        new
                        {
                            Id = 85,
                            Number = 887448560L
                        },
                        new
                        {
                            Id = 86,
                            Number = -1289228135L
                        },
                        new
                        {
                            Id = 87,
                            Number = -401779575L
                        },
                        new
                        {
                            Id = 88,
                            Number = -1691007710L
                        },
                        new
                        {
                            Id = 89,
                            Number = -2092787285L
                        },
                        new
                        {
                            Id = 90,
                            Number = 511172301L
                        },
                        new
                        {
                            Id = 91,
                            Number = -1581614984L
                        },
                        new
                        {
                            Id = 92,
                            Number = -1070442683L
                        },
                        new
                        {
                            Id = 93,
                            Number = 1642909629L
                        },
                        new
                        {
                            Id = 94,
                            Number = 572466946L
                        },
                        new
                        {
                            Id = 95,
                            Number = -2079590721L
                        },
                        new
                        {
                            Id = 96,
                            Number = -1507123775L
                        },
                        new
                        {
                            Id = 97,
                            Number = 708252800L
                        },
                        new
                        {
                            Id = 98,
                            Number = -798870975L
                        },
                        new
                        {
                            Id = 99,
                            Number = -90618175L
                        },
                        new
                        {
                            Id = 100,
                            Number = -889489150L
                        });
                });

            modelBuilder.Entity("GeeksBank.Core.Infrastructure.Models.Results", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
